### ISSUE TITLE
no explicit reference to test environment

### ISSUE THREAD

**Issue by eliasmalik** [oliverjam/learn-unit-testing#2]
`index.html` includes the `test-helpers.js` file to provide the same test utilities as in the `learn-testing` workshop, but this isn't explicitly mentioned in the README. 

I don't know if this was deliberate. I don't dislike not mentioning it, IMO it's not a bad idea to have people hunt around the repo/code, but just checking it's an active decision.

**Comment by oliverjam** [comment]
Hmm at this point I think maybe everything should be explicit. I could compromise on some comments above the script tags explaining what each is for
