### ISSUE TITLE
object & array equality

### ISSUE THREAD

**Issue by eliasmalik** [oliverjam/learn-unit-testing#3]
The "deep equality" section describes a workaround for objects, but not doesn't explicitly mention a workaround for arrays. Could just add a simple `"...(or, equivalently, elements)..."` to the last sentence.

Also, on a pedantic note, the workaround would establish that the desired properties (respectively, elements) _are_ present, but not that they are the _only_ properties (respectively, elements).

I don't know if you want to mention/cover this, I don't think it's a big deal, but just thought I'd mention it.

**Comment by oliverjam** [comment]
Yeah trying to ease them into this. I'm not gonna make them write a deepEqual function so they won't have to worry too much about it until they learn Tape.

I will mention arrays and maybe clarify that the objects could have additional properties.
